'use client'

import { createContext, useContext, useState, ReactNode } from 'react'

export type Lang = 'en' | 'hi' | 'gu'

export const strings = {
  en: {
    // Identity
    eventDates:        'Wed 20 – Fri 22 January 2027',
    namesLine:         'Sakshi & Dr. Sahil',
    hashtag:           '#SakshiKoMilaKinara',
    deadline:          '20 October 2026',

    // Root ("/") — neutral entry, no audience content of its own
    rootEyebrow:       'Together, a more beautiful tomorrow',
    rootHeading:       'Welcome to our celebrations',
    rootIntro:         'From a solo journey to a shared forever.',
    rootBrideChoice:   'Sakshi’s Guests',
    rootBrideChoiceBody: 'Explore the four celebrations and what to wear.',
    rootGroomChoice:   'Dr. Sahil’s Guests',
    rootGroomChoiceBody: 'Confirm your travel details and explore the celebrations.',
    rootContinueAs:    'Continue as {name} →',

    // Countdown (Hero)
    countdownDays:     'Days',
    countdownHours:    'Hours',
    countdownMinutes:  'Min',
    countdownSeconds:  'Sec',

    // Audience — bride
    bridePrimaryCTA:   'Explore Our Celebrations',
    brideSecondaryCTA: 'Download Themes & What to Wear',
    wardrobeExploreCTA: 'Explore Themes & What to Wear',
    brideEyebrow:      'The Celebrations',
    brideDownloadLabel: 'Download the Guest Guide',

    // Audience — groom
    groomPrimaryCTA:   'Confirm Travel Details',
    groomSecondaryCTA: 'Explore Themes & What to Wear',
    groomEyebrow:      'Our Wedding · 20 – 22 January 2027',
    groomDeadlineLine: 'Please share your travel details by 20 October 2026.',
    groomHeroTagline:  'Confirm your travel for our wedding celebrations · Pitampura, Delhi',
    groomArrivalCareHeading: 'Let us take care of your arrival',
    groomArrivalCareBody: 'Your travel details, photo ID and stay.',
    groomDownloadLabel: 'Download the Guest Guide',
    reminderHeading:   'A Quick Reminder',
    reminderBody:      'Please share your travel details with us by',
    travelHeading:     'Getting Here',
    stepGettingToDelhi: 'Step 1 — Getting to Delhi',
    stepOnceInDelhi:   'Step 2 — Once you’re in Delhi',
    travelBody1:       'Fly into Delhi (DEL) or take the train, then share your arrival details below — what happens next depends on your arrival date.',
    travelBody2:       'Arriving on 20 January: we can coordinate your pickup once we have your details. Arriving on 21 January: please arrange your own transport to the venue — we’ll take care of everything once you’re there.',

    // "For the lovely ladies" — groom side only
    lovelyLadiesHeading: 'For the Lovely Ladies',
    lovelyLadiesIntro: 'A little extra, just for you.',
    lovelyLadiesMehndiCardTitle: 'Share Your Mehndi Preference',
    lovelyLadiesMehndiCardBody: 'Joining us on 20 January? Let us know your hand preference.',
    lovelyLadiesMehndiCardCTA: 'Share Your Preference',
    lovelyLadiesMakeupCardTitle: 'Explore the Makeup Guide',
    lovelyLadiesMakeupCardBody: 'A few nearby salons to make getting ready easier.',
    lovelyLadiesMakeupCardCTA: 'Open the Guide',

    // Mehndi RSVP (groom side, #mehndi-rsvp)
    mehndiEyebrow:     'Mehndi · 20 January 2027 · 11 am–2 pm',
    mehndiIntro:       'For the lovely ladies: please let us know your Mehndi preference so we can plan a lovely afternoon for everyone.',
    mehndiYourName:    'Your Name',
    mehndiYourMobile:  'Your Mobile Number',
    mehndiGuestNameLabel: 'Guest Name',
    mehndiAddGuest:    '+ Add Another Guest',
    mehndiRemoveGuest: 'Remove',
    mehndiStatusLabel: 'Will she join the Mehndi?',
    mehndiStatusJoining: 'Joining',
    mehndiStatusUnable: 'Unable to Join',
    mehndiStatusNotSure: 'Not Sure Yet',
    mehndiHandLabel:   'Mehndi Preference',
    mehndiHandOne:     'One Hand',
    mehndiHandBoth:    'Both Hands',
    mehndiReviewBtn:   'Review Before Submitting',
    mehndiReviewHeading: 'Please Review',
    mehndiReviewIntro: 'Everything look right? You can still make changes below.',
    mehndiEditBtn:     'Edit',
    mehndiSubmitBtn:   'Confirm Mehndi Preferences',
    mehndiSending:     'Sending…',
    mehndiSuccessHeading: 'Thank You.',
    mehndiSuccessBody: 'We\'ve received your Mehndi preferences.\nWe can\'t wait to celebrate with you.',
    mehndiErrorGeneric: 'Something went wrong. Please try again.',
    mehndiMissingNameError: 'Please enter your name and mobile number.',

    // Makeup guide (groom side, /groom/makeup)
    makeupEyebrow:     'For the Lovely Ladies',
    makeupHeading:     'Your Makeup, Your Choice',
    makeupBody1:       'Makeup is personal. We\'ve put together a few nearby Pitampura salons to make exploring easier, or you can choose an artist you already love. Please contact, book and pay your chosen salon directly, and arrange your ride from the hotel and back.',
    makeupTimingHeading: '20 & 21 January · 3–5 pm',
    makeupTimingBody:  'This is the entire two-hour window for the trip to the salon, makeup, and the trip back. We\'re in the heart of Pitampura, with nearby salons easy to reach. Please be back at the hotel by or before 5 pm.',
    makeupDisclaimer:  'These salons are starting points, not appointments we\'ve arranged — please check services, rates and available slots directly.',
    makeupOpenBtn:     'Open / Download the Makeup Guide',

    // Navigation
    navHome:           'Home',
    navCelebrations:    'Celebrations',
    navThemes:          'Themes & What to Wear',
    navTravel:          'Travel Details',
    switchToBride:      'Switch to Sakshi’s guests',
    switchToGroom:      'Switch to Dr. Sahil’s guests',

    // Chapters preview (homepage)
    chaptersPreviewHeading: 'Four celebrations. One shared forever.',
    chaptersPreviewBody:    'Discover the story behind each celebration — and what to wear.',
    chaptersPreviewLink:    'Explore the Chapters',

    // Personal interlude (homepage)
    interludeText:     'We can\'t wait to celebrate with you.',

    // Travel & ID confirmation (form)
    travelConfirmEyebrow: 'Please Confirm',
    travelConfirmHeading: 'Confirm Your Travel & Stay',
    travelConfirmIntro:   'Please share your arrival details and a photo of your ID — it helps us arrange your pickup (if you’re arriving 20 January) and your stay.',
    fullName:          'Full Name',
    mobile:            'Mobile Number',
    byFlight:          'By Flight',
    byTrain:           'By Train',
    byRoad:            'By Road',
    arrivalModeLabel:  'How are you arriving?',
    arrivalDate:       'Arrival Date',
    arrivalTime:       'Arrival Time',
    arrivalTimeHint:   'Delhi local time (IST)',
    travelNumber:      'Flight / Train Number',
    flightNumberLabel: 'Flight Number',
    trainNumberLabel:  'Train Number',
    roadDetailsLabel:  'Vehicle / Route',
    departureDate:     'Departure Date',
    guestNamesLabel:   'Names of guests travelling with you',
    idUploadLabel:     'Upload ID Proof',
    idUploadHint:      'Aadhar, Passport, or Driving Licence — for yourself and anyone travelling with you. Used only to arrange your pickup and stay.',
    notesLabel:        'Anything else we should know?',
    travelConfirmBtn:  'Confirm Travel Details',
    sending:           'Sending…',
    travelSuccessHeading: 'All Set.',
    travelSuccessBody: 'We\'ve received your travel details and ID.\nWe\'ll be in touch about your pickup and stay soon.',
    travelSuccessThemesLink: 'Explore Themes & What to Wear',
    chooseFiles:       'Choose Files',
    uploadingLabel:    'Uploading…',
    optionalTag:       '(optional)',
    travelDetailsError: 'Couldn\'t reach the server. Please check your connection and try again.',
    stepAboutTitle:    'About You',
    stepArrivalTitle:  'Your Arrival',
    stepFinalTitle:    'ID & Notes',
    whatToWearShort:   'What to Wear',
    travelBackHeading: 'Ready to Confirm Your Travel?',
    bridePdfHeading:   'Keep the Full Guide Handy',
    forMen:            'For Men',
    forWomen:          'For Women',
    wardrobeCTAHeading: 'See exactly what to wear, chapter by chapter.',
  },
  hi: {
    eventDates:        'बुध 20 – शुक्र 22 जनवरी 2027',
    namesLine:         'साक्षी और डॉ. सहिल',
    hashtag:           '#SakshiKoMilaKinara',
    deadline:          '20 अक्टूबर 2026',

    rootEyebrow:       'साथ में, एक और खूबसूरत कल',
    rootHeading:       'हमारे उत्सव में आपका स्वागत है',
    rootIntro:         'एक अकेली यात्रा से एक साझा भविष्य तक।',
    rootBrideChoice:   'साक्षी के मेहमान',
    rootBrideChoiceBody: 'चारों उत्सव और पहनावा देखें।',
    rootGroomChoice:   'डॉ. सहिल के मेहमान',
    rootGroomChoiceBody: 'अपनी यात्रा विवरण की पुष्टि करें और उत्सव देखें।',
    rootContinueAs:    '{name} के रूप में जारी रखें →',

    countdownDays:     'दिन',
    countdownHours:    'घंटे',
    countdownMinutes:  'मिनट',
    countdownSeconds:  'सेकंड',

    bridePrimaryCTA:   'हमारे उत्सव देखें',
    brideSecondaryCTA: 'थीम्स और पहनावा डाउनलोड करें',
    wardrobeExploreCTA: 'थीम्स और पहनावा देखें',
    brideEyebrow:      'उत्सव',
    brideDownloadLabel: 'गेस्ट गाइड डाउनलोड करें',

    groomPrimaryCTA:   'यात्रा विवरण की पुष्टि करें',
    groomSecondaryCTA: 'थीम्स और पहनावा देखें',
    groomEyebrow:      'हमारी शादी · 20 – 22 जनवरी 2027',
    groomDeadlineLine: 'कृपया अपनी यात्रा जानकारी 20 अक्टूबर 2026 तक साझा करें।',
    groomHeroTagline:  'हमारे विवाह समारोहों के लिए अपनी यात्रा की पुष्टि करें · Pitampura, Delhi',
    groomArrivalCareHeading: 'हमें आपके आगमन का ख्याल रखने दें',
    groomArrivalCareBody: 'आपकी यात्रा जानकारी, पहचान पत्र और ठहरना।',
    groomDownloadLabel: 'गेस्ट गाइड डाउनलोड करें',
    reminderHeading:   'एक त्वरित अनुस्मारक',
    reminderBody:      'कृपया अपनी यात्रा जानकारी हमें इस तारीख तक साझा करें:',
    travelHeading:     'यहाँ कैसे पहुँचें',
    stepGettingToDelhi: 'चरण 1 — दिल्ली पहुँचना',
    stepOnceInDelhi:   'चरण 2 — दिल्ली पहुँचने के बाद',
    travelBody1:       'दिल्ली (DEL) के लिए फ़्लाइट लें या ट्रेन से आएं, फिर नीचे अपनी आगमन जानकारी साझा करें — आगे की व्यवस्था आपकी आगमन तारीख पर निर्भर करती है।',
    travelBody2:       '20 जनवरी को पहुँच रहे हैं: आपकी जानकारी मिलते ही हम आपकी पिकअप का समन्वय कर सकते हैं। 21 जनवरी को पहुँच रहे हैं: कृपया वेन्यू तक की अपनी यात्रा स्वयं व्यवस्थित करें — वहाँ पहुँचने के बाद बाकी सब हम संभाल लेंगे।',

    lovelyLadiesHeading: 'प्रिय महिला मेहमानों के लिए',
    lovelyLadiesIntro: 'आपके लिए कुछ खास।',
    lovelyLadiesMehndiCardTitle: 'अपनी मेहंदी पसंद बताएं',
    lovelyLadiesMehndiCardBody: '20 जनवरी को शामिल हो रही हैं? अपनी हाथ की पसंद बताएं।',
    lovelyLadiesMehndiCardCTA: 'अपनी पसंद बताएं',
    lovelyLadiesMakeupCardTitle: 'मेकअप गाइड देखें',
    lovelyLadiesMakeupCardBody: 'तैयार होना आसान बनाने के लिए कुछ नज़दीकी सैलून।',
    lovelyLadiesMakeupCardCTA: 'गाइड खोलें',

    mehndiEyebrow:     'मेहंदी · 20 जनवरी 2027 · सुबह 11 – दोपहर 2 बजे',
    mehndiIntro:       'प्रिय महिला मेहमानों के लिए: कृपया अपनी मेहंदी पसंद बताएं ताकि हम सभी के लिए एक सुंदर दोपहर की योजना बना सकें।',
    mehndiYourName:    'आपका नाम',
    mehndiYourMobile:  'आपका मोबाइल नंबर',
    mehndiGuestNameLabel: 'मेहमान का नाम',
    mehndiAddGuest:    '+ एक और मेहमान जोड़ें',
    mehndiRemoveGuest: 'हटाएं',
    mehndiStatusLabel: 'क्या वह मेहंदी में शामिल होंगी?',
    mehndiStatusJoining: 'शामिल होंगी',
    mehndiStatusUnable: 'शामिल नहीं हो पाएंगी',
    mehndiStatusNotSure: 'अभी तय नहीं',
    mehndiHandLabel:   'मेहंदी पसंद',
    mehndiHandOne:     'एक हाथ',
    mehndiHandBoth:    'दोनों हाथ',
    mehndiReviewBtn:   'सबमिट करने से पहले जांचें',
    mehndiReviewHeading: 'कृपया जांच लें',
    mehndiReviewIntro: 'सब कुछ सही लग रहा है? आप नीचे बदलाव भी कर सकती हैं।',
    mehndiEditBtn:     'संपादित करें',
    mehndiSubmitBtn:   'मेहंदी पसंद की पुष्टि करें',
    mehndiSending:     'भेजा जा रहा है…',
    mehndiSuccessHeading: 'धन्यवाद।',
    mehndiSuccessBody: 'हमें आपकी मेहंदी पसंद मिल गई है।\nहम आपके साथ जश्न मनाने के लिए बेताब हैं।',
    mehndiErrorGeneric: 'कुछ गलत हो गया। कृपया फिर से प्रयास करें।',
    mehndiMissingNameError: 'कृपया अपना नाम और मोबाइल नंबर दर्ज करें।',

    makeupEyebrow:     'प्रिय महिला मेहमानों के लिए',
    makeupHeading:     'आपका मेकअप, आपकी पसंद',
    makeupBody1:       'मेकअप व्यक्तिगत पसंद है। हमने खोज आसान बनाने के लिए पितमपुरा के कुछ नज़दीकी सैलून चुने हैं, या आप अपनी पसंदीदा आर्टिस्ट चुन सकती हैं। कृपया अपने चुने हुए सैलून से सीधे संपर्क करें, बुकिंग करें और भुगतान करें, और होटल से आने-जाने की व्यवस्था स्वयं करें।',
    makeupTimingHeading: '20 और 21 जनवरी · दोपहर 3–5 बजे',
    makeupTimingBody:  'यह सैलून जाने, मेकअप कराने और वापस आने के लिए पूरी दो घंटे की समय-सीमा है। हम पितमपुरा के मध्य में हैं, जहां नज़दीकी सैलून आसानी से पहुंचा जा सकता है। कृपया शाम 5 बजे तक या उससे पहले होटल लौट आएं।',
    makeupDisclaimer:  'ये सैलून केवल शुरुआती सुझाव हैं, हमारे द्वारा बुक की गई अपॉइंटमेंट नहीं — कृपया सेवाएं, दरें और उपलब्ध समय सीधे जांच लें।',
    makeupOpenBtn:     'मेकअप गाइड खोलें / डाउनलोड करें',

    navHome:           'होम',
    navCelebrations:    'उत्सव',
    navThemes:          'थीम्स और पहनावा',
    navTravel:          'यात्रा विवरण',
    switchToBride:      'साक्षी के मेहमानों पर जाएं',
    switchToGroom:      'डॉ. सहिल के मेहमानों पर जाएं',

    chaptersPreviewHeading: 'चार उत्सव। एक साझा भविष्य।',
    chaptersPreviewBody:    'हर उत्सव की कहानी जानें — और क्या पहनना है।',
    chaptersPreviewLink:    'सभी अध्याय देखें',

    interludeText:     'हम आपके साथ जश्न मनाने के लिए बेताब हैं।',

    travelConfirmEyebrow: 'कृपया पुष्टि करें',
    travelConfirmHeading: 'अपनी यात्रा और ठहरने की पुष्टि करें',
    travelConfirmIntro:   'कृपया अपनी आगमन जानकारी और पहचान पत्र की एक फोटो साझा करें — इससे हमें आपकी पिकअप (यदि 20 जनवरी को आ रहे हैं) और ठहरने की व्यवस्था करने में मदद मिलेगी।',
    fullName:          'पूरा नाम',
    mobile:            'मोबाइल नंबर',
    byFlight:          'हवाई जहाज़ से',
    byTrain:           'ट्रेन से',
    byRoad:            'सड़क से',
    arrivalModeLabel:  'आप कैसे पहुँच रहे हैं?',
    arrivalDate:       'आगमन की तारीख',
    arrivalTime:       'आगमन का समय',
    arrivalTimeHint:   'दिल्ली का स्थानीय समय (IST)',
    travelNumber:      'फ़्लाइट / ट्रेन नंबर',
    flightNumberLabel: 'फ़्लाइट नंबर',
    trainNumberLabel:  'ट्रेन नंबर',
    roadDetailsLabel:  'वाहन / मार्ग',
    departureDate:     'प्रस्थान की तारीख',
    guestNamesLabel:   'आपके साथ आने वाले मेहमानों के नाम',
    idUploadLabel:     'पहचान पत्र अपलोड करें',
    idUploadHint:      'आधार, पासपोर्ट, या ड्राइविंग लाइसेंस — अपने और साथ आने वाले सभी के लिए। केवल आपकी पिकअप और ठहरने की व्यवस्था के लिए उपयोग किया जाएगा।',
    notesLabel:        'कुछ और बताना चाहेंगे?',
    travelConfirmBtn:  'यात्रा विवरण की पुष्टि करें',
    sending:           'भेजा जा रहा है…',
    travelSuccessHeading: 'हो गया।',
    travelSuccessBody: 'हमें आपकी यात्रा जानकारी और पहचान पत्र मिल गया है।\nहम जल्द ही आपकी पिकअप और ठहरने के बारे में संपर्क करेंगे।',
    travelSuccessThemesLink: 'थीम्स और पहनावा देखें',
    chooseFiles:       'फ़ाइलें चुनें',
    uploadingLabel:    'अपलोड हो रहा है…',
    optionalTag:       '(वैकल्पिक)',
    travelDetailsError: 'सर्वर तक नहीं पहुँच सके। कृपया अपना कनेक्शन जाँचें और फिर से प्रयास करें।',
    stepAboutTitle:    'आपके बारे में',
    stepArrivalTitle:  'आपका आगमन',
    stepFinalTitle:    'ID और नोट्स',
    whatToWearShort:   'क्या पहनें',
    travelBackHeading: 'यात्रा की पुष्टि करने के लिए तैयार हैं?',
    bridePdfHeading:   'पूरी गाइड अपने पास रखें',
    forMen:            'पुरुषों के लिए',
    forWomen:          'महिलाओं के लिए',
    wardrobeCTAHeading: 'हर अध्याय का पूरा ड्रेस कोड यहाँ देखें।',
  },
  gu: {
    eventDates:        'બુધ 20 – શુક્ર 22 જાન્યુઆરી 2027',
    namesLine:         'સાક્ષી અને ડૉ. સહિલ',
    hashtag:           '#SakshiKoMilaKinara',
    deadline:          '20 ઓક્ટોબર 2026',

    rootEyebrow:       'સાથે, વધુ સુંદર આવતીકાલ',
    rootHeading:       'અમારા ઉત્સવોમાં તમારું સ્વાગત છે',
    rootIntro:         'એકલી મુસાફરીથી એક સહિયારા ભવિષ્ય સુધી.',
    rootBrideChoice:   'સાક્ષીના મહેમાનો',
    rootBrideChoiceBody: 'ચારેય ઉત્સવો અને શું પહેરવું તે જુઓ.',
    rootGroomChoice:   'ડૉ. સહિલના મહેમાનો',
    rootGroomChoiceBody: 'તમારી મુસાફરીની વિગતોની પુષ્ટિ કરો અને ઉત્સવો જુઓ.',
    rootContinueAs:    '{name} તરીકે ચાલુ રાખો →',

    countdownDays:     'દિવસ',
    countdownHours:    'કલાક',
    countdownMinutes:  'મિનિટ',
    countdownSeconds:  'સેકન્ડ',

    bridePrimaryCTA:   'અમારા ઉત્સવો જુઓ',
    brideSecondaryCTA: 'થીમ્સ અને પોશાક ડાઉનલોડ કરો',
    wardrobeExploreCTA: 'થીમ્સ અને પોશાક જુઓ',
    brideEyebrow:      'ઉત્સવો',
    brideDownloadLabel: 'ગેસ્ટ ગાઇડ ડાઉનલોડ કરો',

    groomPrimaryCTA:   'મુસાફરીની વિગતોની પુષ્ટિ કરો',
    groomSecondaryCTA: 'થીમ્સ અને પોશાક જુઓ',
    groomEyebrow:      'અમારાં લગ્ન · 20 – 22 જાન્યુઆરી 2027',
    groomDeadlineLine: 'કૃપા કરી તમારી મુસાફરીની વિગતો 20 ઓક્ટોબર 2026 સુધીમાં શેર કરો.',
    groomHeroTagline:  'અમારા લગ્ન સમારંભો માટે તમારી મુસાફરીની પુષ્ટિ કરો · Pitampura, Delhi',
    groomArrivalCareHeading: 'અમને તમારા આગમનની કાળજી લેવા દો',
    groomArrivalCareBody: 'તમારી મુસાફરીની વિગતો, ID અને રોકાણ.',
    groomDownloadLabel: 'ગેસ્ટ ગાઇડ ડાઉનલોડ કરો',
    reminderHeading:   'એક ઝડપી યાદ અપાવવું',
    reminderBody:      'કૃપા કરી તમારી મુસાફરીની વિગતો અમને આ તારીખ સુધીમાં શેર કરો:',
    travelHeading:     'અહીં કેવી રીતે પહોંચવું',
    stepGettingToDelhi: 'પગલું 1 — દિલ્હી પહોંચવું',
    stepOnceInDelhi:   'પગલું 2 — દિલ્હી પહોંચ્યા પછી',
    travelBody1:       'દિલ્હી (DEL) માટે ફ્લાઇટ લો અથવા ટ્રેનથી આવો, પછી નીચે તમારી આગમનની વિગતો શેર કરો — આગળની વ્યવસ્થા તમારી આગમન તારીખ પર આધારિત છે.',
    travelBody2:       '20 જાન્યુઆરીએ પહોંચી રહ્યા છો: તમારી વિગતો મળતાં જ અમે તમારું પિકઅપ ગોઠવવાનો પ્રયત્ન કરી શકીએ છીએ. 21 જાન્યુઆરીએ પહોંચી રહ્યા છો: કૃપા કરી વેન્યુ સુધીની તમારી મુસાફરી જાતે ગોઠવો — ત્યાં પહોંચ્યા પછી બાકીનું બધું અમે સંભાળી લઈશું.',

    lovelyLadiesHeading: 'પ્રિય મહિલા મહેમાનો માટે',
    lovelyLadiesIntro: 'તમારા માટે કંઈક ખાસ.',
    lovelyLadiesMehndiCardTitle: 'તમારી મહેંદી પસંદગી જણાવો',
    lovelyLadiesMehndiCardBody: '20 જાન્યુઆરીએ જોડાઈ રહ્યા છો? તમારી હાથની પસંદગી જણાવો.',
    lovelyLadiesMehndiCardCTA: 'તમારી પસંદગી જણાવો',
    lovelyLadiesMakeupCardTitle: 'મેકઅપ ગાઇડ જુઓ',
    lovelyLadiesMakeupCardBody: 'તૈયાર થવાનું સરળ બનાવવા માટે થોડાં નજીકનાં સલૂન.',
    lovelyLadiesMakeupCardCTA: 'ગાઇડ ખોલો',

    mehndiEyebrow:     'મહેંદી · 20 જાન્યુઆરી 2027 · સવારે 11 – બપોરે 2 વાગ્યા',
    mehndiIntro:       'પ્રિય મહિલા મહેમાનો માટે: કૃપા કરી તમારી મહેંદી પસંદગી જણાવો જેથી અમે બધા માટે એક સુંદર બપોર ગોઠવી શકીએ.',
    mehndiYourName:    'તમારું નામ',
    mehndiYourMobile:  'તમારો મોબાઈલ નંબર',
    mehndiGuestNameLabel: 'મહેમાનનું નામ',
    mehndiAddGuest:    '+ બીજા મહેમાન ઉમેરો',
    mehndiRemoveGuest: 'દૂર કરો',
    mehndiStatusLabel: 'શું તેઓ મહેંદીમાં જોડાશે?',
    mehndiStatusJoining: 'જોડાશે',
    mehndiStatusUnable: 'જોડાઈ શકશે નહીં',
    mehndiStatusNotSure: 'હજુ નક્કી નથી',
    mehndiHandLabel:   'મહેંદી પસંદગી',
    mehndiHandOne:     'એક હાથ',
    mehndiHandBoth:    'બંને હાથ',
    mehndiReviewBtn:   'સબમિટ કરતાં પહેલાં તપાસો',
    mehndiReviewHeading: 'કૃપા કરી તપાસો',
    mehndiReviewIntro: 'બધું બરાબર લાગે છે? તમે નીચે ફેરફાર પણ કરી શકો છો.',
    mehndiEditBtn:     'સંપાદિત કરો',
    mehndiSubmitBtn:   'મહેંદી પસંદગીની પુષ્ટિ કરો',
    mehndiSending:     'મોકલાઈ રહ્યું છે…',
    mehndiSuccessHeading: 'આભાર.',
    mehndiSuccessBody: 'અમને તમારી મહેંદી પસંદગીઓ મળી ગઈ છે.\nઅમે તમારી સાથે ઉજવણી કરવા આતુર છીએ.',
    mehndiErrorGeneric: 'કંઈક ખોટું થયું. કૃપા કરી ફરી પ્રયાસ કરો.',
    mehndiMissingNameError: 'કૃપા કરી તમારું નામ અને મોબાઈલ નંબર દાખલ કરો.',

    makeupEyebrow:     'પ્રિય મહિલા મહેમાનો માટે',
    makeupHeading:     'તમારો મેકઅપ, તમારી પસંદગી',
    makeupBody1:       'મેકઅપ વ્યક્તિગત પસંદગી છે. શોધવાનું સરળ બનાવવા અમે પિતમપુરાનાં થોડાં નજીકનાં સલૂન પસંદ કર્યાં છે, અથવા તમે તમારી મનપસંદ આર્ટિસ્ટ પસંદ કરી શકો છો. કૃપા કરી તમારા પસંદ કરેલા સલૂનનો સીધો સંપર્ક કરો, બુક કરો અને ચુકવણી કરો, અને હોટેલથી આવવા-જવાની વ્યવસ્થા જાતે કરો.',
    makeupTimingHeading: '20 અને 21 જાન્યુઆરી · બપોરે 3–5 વાગ્યા',
    makeupTimingBody:  'આ સલૂન જવા, મેકઅપ કરાવવા અને પાછા આવવા માટેની સંપૂર્ણ બે-કલાકની સમય-મર્યાદા છે. અમે પિતમપુરાના મધ્યમાં છીએ, જ્યાં નજીકનાં સલૂન સરળતાથી પહોંચી શકાય છે. કૃપા કરી સાંજે 5 વાગ્યા સુધીમાં અથવા તે પહેલાં હોટેલ પરત ફરો.',
    makeupDisclaimer:  'આ સલૂન ફક્ત શરૂઆતના સૂચનો છે, અમે બુક કરેલી એપોઇન્ટમેન્ટ નથી — કૃપા કરી સેવાઓ, દરો અને ઉપલબ્ધ સમય સીધા તપાસો.',
    makeupOpenBtn:     'મેકઅપ ગાઇડ ખોલો / ડાઉનલોડ કરો',

    navHome:           'હોમ',
    navCelebrations:    'ઉત્સવો',
    navThemes:          'થીમ્સ અને પોશાક',
    navTravel:          'મુસાફરીની વિગતો',
    switchToBride:      'સાક્ષીના મહેમાનો પર જાઓ',
    switchToGroom:      'ડૉ. સહિલના મહેમાનો પર જાઓ',

    chaptersPreviewHeading: 'ચાર ઉત્સવો. એક સહિયારું ભવિષ્ય.',
    chaptersPreviewBody:    'દરેક ઉત્સવની વાર્તા જાણો — અને શું પહેરવું.',
    chaptersPreviewLink:    'બધા પ્રકરણો જુઓ',

    interludeText:     'અમે તમારી સાથે ઉજવણી કરવા આતુર છીએ.',

    travelConfirmEyebrow: 'કૃપા કરી પુષ્ટિ કરો',
    travelConfirmHeading: 'તમારી મુસાફરી અને રોકાણની પુષ્ટિ કરો',
    travelConfirmIntro:   'કૃપા કરી તમારી આગમનની વિગતો અને ID નો ફોટો શેર કરો — આનાથી અમને તમારું પિકઅપ (જો 20 જાન્યુઆરીએ પહોંચી રહ્યા હો) અને રોકાણ ગોઠવવામાં મદદ મળશે.',
    fullName:          'પૂરું નામ',
    mobile:            'મોબાઈલ નંબર',
    byFlight:          'વિમાનથી',
    byTrain:           'ટ્રેનથી',
    byRoad:            'રસ્તા દ્વારા',
    arrivalModeLabel:  'તમે કઈ રીતે પહોંચી રહ્યા છો?',
    arrivalDate:       'આગમનની તારીખ',
    arrivalTime:       'આગમનનો સમય',
    arrivalTimeHint:   'દિલ્હીનો સ્થાનિક સમય (IST)',
    travelNumber:      'ફ્લાઇટ / ટ્રેન નંબર',
    flightNumberLabel: 'ફ્લાઇટ નંબર',
    trainNumberLabel:  'ટ્રેન નંબર',
    roadDetailsLabel:  'વાહન / રૂટ',
    departureDate:     'પ્રસ્થાનની તારીખ',
    guestNamesLabel:   'તમારી સાથે આવતા મહેમાનોના નામ',
    idUploadLabel:     'ID પુરાવો અપલોડ કરો',
    idUploadHint:      'આધાર, પાસપોર્ટ, અથવા ડ્રાઇવિંગ લાઇસન્સ — તમારા માટે અને સાથે આવતા બધા માટે. ફક્ત તમારું પિકઅપ અને રોકાણ ગોઠવવા માટે ઉપયોગમાં લેવાશે.',
    notesLabel:        'બીજું કંઈ જણાવવું છે?',
    travelConfirmBtn:  'મુસાફરીની વિગતોની પુષ્ટિ કરો',
    sending:           'મોકલાઈ રહ્યું છે…',
    travelSuccessHeading: 'થઈ ગયું.',
    travelSuccessBody: 'અમને તમારી મુસાફરીની વિગતો અને ID મળી ગયા છે.\nઅમે ટૂંક સમયમાં તમારા પિકઅપ અને રોકાણ વિશે સંપર્ક કરીશું.',
    travelSuccessThemesLink: 'થીમ્સ અને પોશાક જુઓ',
    chooseFiles:       'ફાઇલો પસંદ કરો',
    uploadingLabel:    'અપલોડ થઈ રહ્યું છે…',
    optionalTag:       '(વૈકલ્પિક)',
    travelDetailsError: 'સર્વર સુધી પહોંચી શકાયું નહીં. કૃપા કરી તમારું કનેક્શન તપાસો અને ફરી પ્રયાસ કરો.',
    stepAboutTitle:    'તમારા વિશે',
    stepArrivalTitle:  'તમારું આગમન',
    stepFinalTitle:    'ID અને નોંધ',
    whatToWearShort:   'શું પહેરવું',
    travelBackHeading: 'મુસાફરીની પુષ્ટિ કરવા તૈયાર છો?',
    bridePdfHeading:   'સંપૂર્ણ ગાઇડ તમારી પાસે રાખો',
    forMen:            'પુરુષો માટે',
    forWomen:          'મહિલાઓ માટે',
    wardrobeCTAHeading: 'દરેક પ્રકરણનો સંપૂર્ણ ડ્રેસ કોડ અહીં જુઓ.',
  },
}

// ── Themes / wardrobe page content ────────────────────────────────────────
// English is the reviewed source (from the handoff brief). Hindi and
// Gujarati are AI-drafted translations, not yet human-reviewed — flagged
// in the delivery notes.
export const themesStrings = {
  en: {
    heading: 'From a solo journey to a shared forever.',
    intro: 'What began as a solo trip to the hills of Bir became a journey neither of us would take alone.',
    datesLine: '20 – 22 January 2027 · Delhi',
    checkoutNote: '22 January · Checkout',
    closing: 'Four celebrations. Four chapters. One complete journey.',
    inspirationNote: 'The illustrations are inspiration — bring your own style within the theme.',
    wearHeading: 'What to Wear — At a Glance',
    wearIntro: 'A quick reference for all four celebrations. Illustrations are inspiration, not compulsory purchases.',
    men: 'Men',
    women: 'Women',
    palette: 'Palette',
    dressCode: 'Dress code',
    whatToWearEyebrow: 'What to Wear',
    chapterLabel: 'Chapter',
    paletteDisclaimer: 'Palette is the illustration’s decorative colour scheme, not a clothing requirement.',
    dow: { '2027-01-20': 'Wed 20 January', '2027-01-21': 'Thu 21 January' } as Record<string, string>,
    dowShort: { '2027-01-20': 'Wed 20 Jan', '2027-01-21': 'Thu 21 Jan' } as Record<string, string>,
    timeOfDay: { Morning: 'Morning', Evening: 'Evening' } as Record<string, string>,
    chapters: {
      bloom: {
        event: 'Mehendi', story: 'Two strangers meet in the hills.', shortLine: 'Traditions in full bloom.',
        dressCode: 'Florals & pastels with a tint of green',
        menLooks: ['A sage-green floral-embroidered jacket, ivory kurta and white pants', 'A solid blush kurta with white pants'],
        womenLooks: ['A blush lehenga with floral embroidery and a sage dupatta', 'An ivory floral-print saree with a sage border'],
      },
      promise: {
        event: 'Engagement & Cocktail', story: 'Two lives choose a shared forever.', shortLine: 'A toast to what’s ahead.',
        men: 'Tuxedos & Suits',
        women: 'Gowns only',
        menLooks: ['A classic navy tuxedo', 'A deep plum three-piece suit'],
        womenLooks: ['A hot-pink tiered evening gown', 'An emerald sequinned evening gown'],
        womenLooksNote: 'No saree, lehenga or Indian separates for this one — gowns only.',
      },
      romance: {
        event: 'Haldi', story: 'Every call, trip and moment in between.', shortLine: 'Colours of love.',
        women: 'Hot pink', men: 'Shades of pink — blush, rose or deeper pink', fabricNote: 'Easy, Haldi-friendly fabrics',
        menLooks: ['A blush-pink embroidered kurta with white pants', 'A deeper rose kurta with white pants'],
        womenLooks: ['A hot-pink embroidered salwar suit', 'A hot-pink saree with gold border work'],
      },
      legacy: {
        event: 'Wedding', story: 'The journey finds its Kinara — its home.', shortLine: 'A love for generations.',
        dressCode: 'Indian formal',
        menLooks: ['An ivory-and-gold embroidered sherwani with a matching dupatta', 'An ivory bandhgala jacket with churidar'],
        womenLooks: ['An ivory-and-gold embroidered saree', 'An ivory-and-gold embroidered lehenga'],
      },
    },
  },
  hi: {
    heading: 'एक अकेली यात्रा से एक साझा भविष्य तक।',
    intro: 'बीर की पहाड़ियों की एक अकेली यात्रा से शुरू हुआ सफ़र, एक ऐसी यात्रा बन गया जो हम दोनों ने साथ तय की।',
    datesLine: '20 – 22 जनवरी 2027 · दिल्ली',
    checkoutNote: '22 जनवरी · चेक-आउट',
    closing: 'चार उत्सव। चार अध्याय। एक संपूर्ण यात्रा।',
    inspirationNote: 'ये चित्र केवल प्रेरणा हैं — थीम के भीतर अपनी शैली अपनाएं।',
    wearHeading: 'क्या पहनें — एक नज़र में',
    wearIntro: 'सभी चार उत्सवों के लिए त्वरित संदर्भ। चित्र केवल प्रेरणा हैं, अनिवार्य खरीद नहीं।',
    men: 'पुरुष',
    women: 'महिलाएं',
    palette: 'रंग पट्टिका',
    dressCode: 'ड्रेस कोड',
    whatToWearEyebrow: 'क्या पहनें',
    chapterLabel: 'अध्याय',
    paletteDisclaimer: 'रंग पट्टिका चित्र की सजावटी रंग योजना है, यह पहनावे की शर्त नहीं है।',
    dow: { '2027-01-20': 'बुध 20 जनवरी', '2027-01-21': 'गुरु 21 जनवरी' } as Record<string, string>,
    dowShort: { '2027-01-20': 'बुध 20 जन', '2027-01-21': 'गुरु 21 जन' } as Record<string, string>,
    timeOfDay: { Morning: 'सुबह', Evening: 'शाम' } as Record<string, string>,
    chapters: {
      bloom: {
        event: 'मेहंदी', story: 'पहाड़ियों में दो अजनबी मिलते हैं।', shortLine: 'परंपराएं पूरे खिलाव में।',
        dressCode: 'हल्के हरे रंग की झलक के साथ फूलों और पेस्टल रंगों वाले परिधान',
        menLooks: ['सेज-ग्रीन फूलों की कढ़ाई वाली जैकेट, आइवरी कुर्ता और सफ़ेद पैंट', 'सादा ब्लश कुर्ता सफ़ेद पैंट के साथ'],
        womenLooks: ['सेज दुपट्टे के साथ फूलों की कढ़ाई वाला ब्लश लहंगा', 'सेज बॉर्डर वाली आइवरी फ्लोरल-प्रिंट साड़ी'],
      },
      promise: {
        event: 'सगाई और कॉकटेल', story: 'दो जिंदगियां एक साझा भविष्य चुनती हैं।', shortLine: 'आने वाले कल के नाम एक जाम।',
        men: 'टक्सीडो और सूट',
        women: 'केवल गाउन',
        menLooks: ['एक क्लासिक नेवी टक्सीडो', 'गहरे बैंगनी रंग का थ्री-पीस सूट'],
        womenLooks: ['हॉट-पिंक टियर्ड इवनिंग गाउन', 'एमराल्ड सेक्विन इवनिंग गाउन'],
        womenLooksNote: 'इस चैप्टर में केवल गाउन — साड़ी, लहंगा या इंडियन सेट नहीं।',
      },
      romance: {
        event: 'हल्दी', story: 'हर कॉल, हर यात्रा और बीच का हर पल।', shortLine: 'प्रेम के रंग।',
        women: 'हॉट पिंक', men: 'गुलाबी की छटाएं — ब्लश, रोज़ या गहरा गुलाबी', fabricNote: 'सहज, हल्दी के लिए उपयुक्त कपड़े',
        menLooks: ['सफ़ेद पैंट के साथ ब्लश-पिंक कढ़ाई वाला कुर्ता', 'सफ़ेद पैंट के साथ गहरे गुलाबी रंग का कुर्ता'],
        womenLooks: ['हॉट-पिंक कढ़ाई वाला सलवार सूट', 'गोल्ड बॉर्डर वर्क वाली हॉट-पिंक साड़ी'],
      },
      legacy: {
        event: 'विवाह', story: 'यात्रा को उसका किनारा — उसका घर मिल जाता है।', shortLine: 'पीढ़ियों के लिए एक प्रेम।',
        dressCode: 'इंडियन फॉर्मल',
        menLooks: ['मैचिंग दुपट्टे के साथ आइवरी-गोल्ड कढ़ाई वाली शेरवानी', 'चूड़ीदार के साथ आइवरी बंदगला जैकेट'],
        womenLooks: ['आइवरी-गोल्ड कढ़ाई वाली साड़ी', 'आइवरी-गोल्ड कढ़ाई वाला लहंगा'],
      },
    },
  },
  gu: {
    heading: 'એકલી મુસાફરીથી એક સહિયારા ભવિષ્ય સુધી.',
    intro: 'બીરની ટેકરીઓની એકલી સફરથી શરૂ થયેલી આ યાત્રા, એવી સફર બની ગઈ જે અમે બંનેએ સાથે મળીને કરી.',
    datesLine: '20 – 22 જાન્યુઆરી 2027 · દિલ્હી',
    checkoutNote: '22 જાન્યુઆરી · ચેક-આઉટ',
    closing: 'ચાર ઉત્સવો. ચાર પ્રકરણો. એક સંપૂર્ણ સફર.',
    inspirationNote: 'આ ચિત્રો ફક્ત પ્રેરણા છે — થીમની અંદર તમારી પોતાની સ્ટાઇલ અપનાવો.',
    wearHeading: 'શું પહેરવું — એક નજરમાં',
    wearIntro: 'ચારેય ઉત્સવો માટે ઝડપી સંદર્ભ. ચિત્રો ફક્ત પ્રેરણા છે, ફરજિયાત ખરીદી નથી.',
    men: 'પુરુષો',
    women: 'મહિલાઓ',
    palette: 'રંગ પૅલેટ',
    dressCode: 'ડ્રેસ કોડ',
    whatToWearEyebrow: 'શું પહેરવું',
    chapterLabel: 'પ્રકરણ',
    paletteDisclaimer: 'રંગ પૅલેટ ચિત્રની સુશોભન રંગ યોજના છે, તે પોશાકની જરૂરિયાત નથી.',
    dow: { '2027-01-20': 'બુધ 20 જાન્યુઆરી', '2027-01-21': 'ગુરુ 21 જાન્યુઆરી' } as Record<string, string>,
    dowShort: { '2027-01-20': 'બુધ 20 જાન', '2027-01-21': 'ગુરુ 21 જાન' } as Record<string, string>,
    timeOfDay: { Morning: 'સવાર', Evening: 'સાંજ' } as Record<string, string>,
    chapters: {
      bloom: {
        event: 'મહેંદી', story: 'ટેકરીઓમાં બે અજાણ્યા લોકો મળે છે.', shortLine: 'પરંપરાઓ પૂર્ણ મોરમાં.',
        dressCode: 'આછા લીલા રંગની ઝલક સાથે ફૂલોવાળા અને પેસ્ટલ પોશાક',
        menLooks: ['સેજ-ગ્રીન ફૂલોની ભરતકામવાળી જેકેટ, આઇવરી કુર્તા અને સફેદ પેન્ટ', 'સફેદ પેન્ટ સાથે સાદો બ્લશ કુર્તા'],
        womenLooks: ['સેજ દુપટ્ટા સાથે ફૂલોની ભરતકામવાળો બ્લશ લહેંગા', 'સેજ બોર્ડરવાળી આઇવરી ફ્લોરલ-પ્રિન્ટ સાડી'],
      },
      promise: {
        event: 'સગાઈ અને કોકટેલ', story: 'બે જિંદગીઓ એક સહિયારું ભવિષ્ય પસંદ કરે છે.', shortLine: 'આગળના રસ્તા માટે એક ટોસ્ટ.',
        men: 'ટક્સિડો અને સૂટ',
        women: 'ફક્ત ગાઉન',
        menLooks: ['એક ક્લાસિક નેવી ટક્સિડો', 'ઘેરા જાંબલી રંગનો થ્રી-પીસ સૂટ'],
        womenLooks: ['હોટ-પિંક ટાયર્ડ ઇવનિંગ ગાઉન', 'એમેરાલ્ડ સિક્વિન ઇવનિંગ ગાઉન'],
        womenLooksNote: 'આ પ્રકરણમાં ફક્ત ગાઉન — સાડી, લહેંગા કે ઇન્ડિયન સેટ નહીં.',
      },
      romance: {
        event: 'હળદી', story: 'દરેક કૉલ, સફર અને વચ્ચેની દરેક ક્ષણ.', shortLine: 'પ્રેમના રંગો.',
        women: 'હોટ પિંક', men: 'ગુલાબી રંગની છટાઓ — બ્લશ, રોઝ અથવા ઘેરો ગુલાબી', fabricNote: 'સરળ, હળદી માટે અનુકૂળ કાપડ',
        menLooks: ['સફેદ પેન્ટ સાથે બ્લશ-પિંક ભરતકામવાળો કુર્તા', 'સફેદ પેન્ટ સાથે ઘેરા ગુલાબી રંગનો કુર્તા'],
        womenLooks: ['હોટ-પિંક ભરતકામવાળો સલવાર સૂટ', 'ગોલ્ડ બોર્ડર વર્કવાળી હોટ-પિંક સાડી'],
      },
      legacy: {
        event: 'લગ્ન', story: 'સફરને તેનો કિનારો — તેનું ઘર મળે છે.', shortLine: 'પેઢીઓ માટેનો પ્રેમ.',
        dressCode: 'ઇન્ડિયન ફોર્મલ',
        menLooks: ['મેચિંગ દુપટ્ટા સાથે આઇવરી-ગોલ્ડ ભરતકામવાળી શેરવાની', 'ચૂડીદાર સાથે આઇવરી બંદગલા જેકેટ'],
        womenLooks: ['આઇવરી-ગોલ્ડ ભરતકામવાળી સાડી', 'આઇવરી-ગોલ્ડ ભરતકામવાળો લહેંગા'],
      },
    },
  },
}

type Strings = typeof strings.en
const LanguageContext = createContext<{
  lang: Lang
  setLang: (l: Lang) => void
  t: Strings
}>({ lang: 'en', setLang: () => {}, t: strings.en })

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>('en')
  return (
    <LanguageContext.Provider value={{ lang, setLang, t: strings[lang] }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLang() {
  return useContext(LanguageContext)
}
