'use client'

import { createContext, useContext, useState, ReactNode } from 'react'

export type Lang = 'en' | 'hi' | 'gu'

export const strings = {
  en: {
    saveTheDate:       'Confirm Travel',
    tapToOpen:         'Tap to open',
    inviteHeading:     'Help Us Take Care of You',
    eventDates:        'Wed 20 – Fri 22 January 2027',
    inviteBody1:       'To arrange your airport pickup and hotel room, we just need your travel details and a quick photo ID from you.',
    inviteBody2:       'Please share these with us by',
    deadline:          '31 October 2026',
    travelHeading:     'Plan Your Travel to Delhi',
    travelBody1:       'January is a busy travel season in India, so we encourage you to book your tickets early — whether you\'re flying, taking the train, or driving in. We can\'t wait to welcome you here!',
    travelBody2:       'From the moment you arrive, everything is taken care of. Your stay and transport to each celebration between the 20th and 22nd are all arranged — so you can simply relax and enjoy the festivities with us.',
    fullName:          'Full Name',
    mobile:            'Mobile Number',
    byFlight:          'By Flight',
    byTrain:           'By Train',
    byRoad:            'By Road',
    sending:           'Sending…',
    weddingOf:         'Wedding of Sakshi & Dr. Sahil',
    namesLine:         'Sakshi & Dr. Sahil',
    confirmTravelBtn:  'Confirm Travel Details',
    themesLinkLabel:   'Themes & What to Wear',
    // Travel reminder (compact, homepage)
    reminderHeading:   'Help us take care of you.',
    reminderBody:      'Please share your travel details and photo ID by',
    // Chapters preview (homepage)
    chaptersPreviewHeading: 'Four celebrations. One shared forever.',
    chaptersPreviewBody:    'Discover the story behind each celebration — and what to wear.',
    chaptersPreviewLink:    'Explore the Chapters',
    // Personal interlude (homepage)
    interludeText:     'We can\'t wait to celebrate with you.',
    // Travel & ID confirmation
    travelConfirmEyebrow: 'Please Confirm',
    travelConfirmHeading: 'Confirm Your Travel & Stay',
    travelConfirmIntro:   'So we can lock in your airport pickup and hotel room, please share your arrival details and a photo of your ID.',
    arrivalModeLabel:  'How are you arriving?',
    arrivalDate:       'Arrival Date',
    arrivalTime:       'Arrival Time',
    arrivalTimeHint:   'Delhi local time (IST)',
    travelNumber:      'Flight / Train Number',
    departureDate:     'Departure Date',
    guestNamesLabel:   'Names of guests travelling with you',
    idUploadLabel:     'Upload ID Proof',
    idUploadHint:      'Aadhar, Passport, or Driving Licence — for yourself and anyone travelling with you. Used only to confirm your pickup and room.',
    notesLabel:        'Anything else we should know?',
    travelConfirmBtn:  'Confirm Travel Details',
    travelSuccessHeading: 'All Set.',
    travelSuccessBody: 'We\'ve received your travel details.\nWe\'ll confirm your pickup and room shortly.',
    chooseFiles:       'Choose Files',
    uploadingLabel:    'Uploading…',
    optionalTag:       '(optional)',
    travelDetailsError: 'Couldn\'t reach the server. Please check your connection and try again.',
    // Footer
    footerThemesLink:  'The Four Chapters & What to Wear',
  },
  hi: {
    saveTheDate:       'यात्रा की पुष्टि करें',
    tapToOpen:         'खोलने के लिए टैप करें',
    inviteHeading:     'हमें आपका ख्याल रखने दें',
    eventDates:        'बुध 20 – शुक्र 22 जनवरी 2027',
    inviteBody1:       'आपकी एयरपोर्ट पिकअप और होटल रूम की व्यवस्था करने के लिए, हमें बस आपकी यात्रा जानकारी और एक पहचान पत्र की फोटो चाहिए।',
    inviteBody2:       'कृपया इन्हें हमें इस तारीख तक साझा करें',
    deadline:          '31 अक्टूबर 2026',
    travelHeading:     'दिल्ली कैसे पहुँचें',
    travelBody1:       'जनवरी में भारत में यात्रा का व्यस्त मौसम होता है, इसलिए हम आपको जल्दी टिकट बुक करने की सलाह देते हैं — हवाई जहाज़ से, ट्रेन से, या सड़क से। हम आपका स्वागत करने के लिए बेताब हैं!',
    travelBody2:       'दिल्ली पहुँचते ही सब कुछ तैयार मिलेगा। 20 से 22 जनवरी के बीच हर उत्सव के लिए आपके रहने और आने-जाने का पूरा इंतज़ाम है — बस आराम से आइए और जश्न का हिस्सा बनिए।',
    fullName:          'पूरा नाम',
    mobile:            'मोबाइल नंबर',
    byFlight:          'हवाई जहाज़ से',
    byTrain:           'ट्रेन से',
    byRoad:            'सड़क से',
    sending:           'भेजा जा रहा है…',
    weddingOf:         'साक्षी और डॉ. सहिल का विवाह',
    namesLine:         'साक्षी और डॉ. सहिल',
    confirmTravelBtn:  'यात्रा विवरण की पुष्टि करें',
    themesLinkLabel:   'चार उत्सव और पहनावा',
    reminderHeading:   'हमें आपका ख्याल रखने दें।',
    reminderBody:      'कृपया अपनी यात्रा जानकारी और पहचान पत्र की फोटो इस तारीख तक साझा करें',
    chaptersPreviewHeading: 'चार उत्सव। एक साझा भविष्य।',
    chaptersPreviewBody:    'हर उत्सव की कहानी जानें — और क्या पहनना है।',
    chaptersPreviewLink:    'सभी अध्याय देखें',
    interludeText:     'हम आपके साथ जश्न मनाने के लिए बेताब हैं।',
    travelConfirmEyebrow: 'कृपया पुष्टि करें',
    travelConfirmHeading: 'अपनी यात्रा और ठहरने की पुष्टि करें',
    travelConfirmIntro:   'आपकी एयरपोर्ट पिकअप और होटल रूम पक्का करने के लिए, कृपया अपनी यात्रा जानकारी और पहचान पत्र की एक फोटो साझा करें।',
    arrivalModeLabel:  'आप कैसे पहुँच रहे हैं?',
    arrivalDate:       'आगमन की तारीख',
    arrivalTime:       'आगमन का समय',
    arrivalTimeHint:   'दिल्ली का स्थानीय समय (IST)',
    travelNumber:      'फ़्लाइट / ट्रेन नंबर',
    departureDate:     'प्रस्थान की तारीख',
    guestNamesLabel:   'आपके साथ आने वाले मेहमानों के नाम',
    idUploadLabel:     'पहचान पत्र अपलोड करें',
    idUploadHint:      'आधार, पासपोर्ट, या ड्राइविंग लाइसेंस — अपने और साथ आने वाले सभी के लिए। केवल पिकअप और कमरे की पुष्टि के लिए उपयोग किया जाएगा।',
    notesLabel:        'कुछ और बताना चाहेंगे?',
    travelConfirmBtn:  'यात्रा विवरण की पुष्टि करें',
    travelSuccessHeading: 'हो गया।',
    travelSuccessBody: 'हमें आपकी यात्रा जानकारी मिल गई है।\nहम जल्द ही आपकी पिकअप और कमरे की पुष्टि करेंगे।',
    chooseFiles:       'फ़ाइलें चुनें',
    uploadingLabel:    'अपलोड हो रहा है…',
    optionalTag:       '(वैकल्पिक)',
    travelDetailsError: 'सर्वर तक नहीं पहुँच सके। कृपया अपना कनेक्शन जाँचें और फिर से प्रयास करें।',
    footerThemesLink:  'चार उत्सव और पहनावा',
  },
  gu: {
    saveTheDate:       'મુસાફરીની પુષ્ટિ કરો',
    tapToOpen:         'ખોલવા ટૅપ કરો',
    inviteHeading:     'અમને તમારી કાળજી લેવા દો',
    eventDates:        'બુધ 20 – શુક્ર 22 જાન્યુઆરી 2027',
    inviteBody1:       'તમારું એરપોર્ટ પિકઅપ અને હોટેલ રૂમ ગોઠવવા માટે, અમને ફક્ત તમારી મુસાફરીની વિગતો અને એક ID ફોટો જોઈએ છે.',
    inviteBody2:       'કૃપા કરી આ અમને આ તારીખ સુધી શેર કરો',
    deadline:          '31 ઓક્ટોબર 2026',
    travelHeading:     'દિલ્હી કેવી રીતે પહોંચશો',
    travelBody1:       'જાન્યુઆરી ભારતમાં પ્રવાસ માટે વ્યસ્ત સિઝન છે, તેથી ટિકિટ વહેલી બૂક કરવા અમે પ્રોત્સાહિત કરીએ છીએ — વિમાનથી, ટ્રેનથી કે સડક માર્ગે. તમારું સ્વાગત કરવા અમે આતુર છીએ!',
    travelBody2:       'દિલ્હી પહોંચ્યા ક્ષણથી, બધું ગોઠવેલ છે. 20 થી 22 જાન્યુઆરી વચ્ચે દરેક ઉત્સવ માટે રહેવા અને ટ્રાન્સ્પોર્ટની સંપૂર્ણ વ્યવસ્થા છે — ફક્ત આરામ કરો અને ઉત્સવ માણો.',
    fullName:          'પૂરું નામ',
    mobile:            'મોબાઈલ નંબર',
    byFlight:          'વિમાનથી',
    byTrain:           'ટ્રેનથી',
    byRoad:            'રસ્તા દ્વારા',
    sending:           'મોકલાઈ રહ્યું છે…',
    weddingOf:         'સાક્ષી અને ડૉ. સહિલના લગ્ન',
    namesLine:         'સાક્ષી અને ડૉ. સહિલ',
    confirmTravelBtn:  'મુસાફરીની વિગતોની પુષ્ટિ કરો',
    themesLinkLabel:   'ચાર ઉત્સવો અને પોશાક',
    reminderHeading:   'અમને તમારી કાળજી લેવા દો.',
    reminderBody:      'કૃપા કરી તમારી મુસાફરીની વિગતો અને ID ફોટો આ તારીખ સુધીમાં શેર કરો',
    chaptersPreviewHeading: 'ચાર ઉત્સવો. એક સહિયારું ભવિષ્ય.',
    chaptersPreviewBody:    'દરેક ઉત્સવની વાર્તા જાણો — અને શું પહેરવું.',
    chaptersPreviewLink:    'બધા પ્રકરણો જુઓ',
    interludeText:     'અમે તમારી સાથે ઉજવણી કરવા આતુર છીએ.',
    travelConfirmEyebrow: 'કૃપા કરી પુષ્ટિ કરો',
    travelConfirmHeading: 'તમારી મુસાફરી અને રોકાણની પુષ્ટિ કરો',
    travelConfirmIntro:   'તમારું એરપોર્ટ પિકઅપ અને હોટેલ રૂમ પાક્કું કરવા, કૃપા કરી તમારી મુસાફરીની વિગતો અને ID નો ફોટો શેર કરો.',
    arrivalModeLabel:  'તમે કઈ રીતે પહોંચી રહ્યા છો?',
    arrivalDate:       'આગમનની તારીખ',
    arrivalTime:       'આગમનનો સમય',
    arrivalTimeHint:   'દિલ્હીનો સ્થાનિક સમય (IST)',
    travelNumber:      'ફ્લાઇટ / ટ્રેન નંબર',
    departureDate:     'પ્રસ્થાનની તારીખ',
    guestNamesLabel:   'તમારી સાથે આવતા મહેમાનોના નામ',
    idUploadLabel:     'ID પુરાવો અપલોડ કરો',
    idUploadHint:      'આધાર, પાસપોર્ટ, અથવા ડ્રાઇવિંગ લાઇસન્સ — તમારા માટે અને સાથે આવતા બધા માટે. ફક્ત પિકઅપ અને રૂમની પુષ્ટિ માટે ઉપયોગમાં લેવાશે.',
    notesLabel:        'બીજું કંઈ જણાવવું છે?',
    travelConfirmBtn:  'મુસાફરીની વિગતોની પુષ્ટિ કરો',
    travelSuccessHeading: 'થઈ ગયું.',
    travelSuccessBody: 'અમને તમારી મુસાફરીની વિગતો મળી ગઈ છે.\nઅમે ટૂંક સમયમાં તમારું પિકઅપ અને રૂમ કન્ફર્મ કરીશું.',
    chooseFiles:       'ફાઇલો પસંદ કરો',
    uploadingLabel:    'અપલોડ થઈ રહ્યું છે…',
    optionalTag:       '(વૈકલ્પિક)',
    travelDetailsError: 'સર્વર સુધી પહોંચી શકાયું નહીં. કૃપા કરી તમારું કનેક્શન તપાસો અને ફરી પ્રયાસ કરો.',
    footerThemesLink:  'ચાર ઉત્સવો અને પોશાક',
  },
}

// ── /themes page content ──────────────────────────────────────────────────
// English is the reviewed source (from the handoff brief). Hindi and
// Gujarati are AI-drafted translations, not yet human-reviewed — flagged
// in the delivery notes.
export const themesStrings = {
  en: {
    nav: { home: 'Home', travel: 'Travel Details', wear: 'What to Wear' },
    heading: 'From a solo journey to a shared forever.',
    intro: 'What began as a solo trip to the hills of Bir became a journey neither of us would take alone.',
    datesLine: '20 – 22 January 2027 · Delhi',
    checkoutNote: '22 January · Checkout',
    closing: 'Four celebrations. Four chapters. One complete journey.',
    backHeading: 'Ready to join us?',
    backCta: 'Confirm Your Travel Details',
    backDeadline: 'Please share your travel details and photo ID by 31 October 2026.',
    wearHeading: 'What to Wear — At a Glance',
    wearIntro: 'A quick reference for all four celebrations. Illustrations are inspiration, not compulsory purchases.',
    men: 'Men',
    women: 'Women',
    palette: 'Palette',
    dressCode: 'Dress code',
    whatToWearEyebrow: 'What to Wear',
    chapterLabel: 'Chapter',
    paletteDisclaimer: 'Palette is the illustration’s decorative colour scheme, not a clothing requirement.',
    dow: { '2027-01-20': 'Wed 20 January', '2027-01-21': 'Thu 21 January' } as Record<string, string>,
    dowShort: { '2027-01-20': 'Wed 20 Jan', '2027-01-21': 'Thu 21 Jan' } as Record<string, string>,
    timeOfDay: { Morning: 'Morning', Evening: 'Evening' } as Record<string, string>,
    chapters: {
      bloom: {
        event: 'Mehendi', story: 'Two strangers meet in the hills.', shortLine: 'Traditions in full bloom.',
        dressCode: 'Florals & pastels with a tint of green',
        outfitExamples: ['Floral or pastel kurta sets', 'Floral lehengas, sarees or easy festive sets'],
      },
      promise: {
        event: 'Engagement & Cocktail', story: 'Two lives choose a shared forever.', shortLine: 'A toast to what’s ahead.',
        men: 'Tuxedos & Suits',
        womenSourceVerbatim: 'Neon Gowns & Evening Indian',
        paletteSourceVerbatim: 'Cocktail Formal · Jewel Tones',
        note: 'Colour palette shown below (navy/emerald/plum/ruby) is a provisional jewel-tone interpretation pending confirmation — the source also says "Neon."',
      },
      romance: {
        event: 'Haldi', story: 'Every call, trip and moment in between.', shortLine: 'Colours of love.',
        dressCode: 'Hot pink', fabricNote: 'Easy, Haldi-friendly fabrics',
        outfitExamples: ['Light hot-pink kurta sets', 'Easy hot-pink salwar suits or sarees'],
      },
      legacy: {
        event: 'Wedding', story: 'The journey finds its Kinara — its home.', shortLine: 'A love for generations.',
        dressCode: 'Indian formal',
        outfitExamples: ['Ivory or champagne sherwanis and formal Indian sets', 'Ivory, champagne or gold sarees and lehengas'],
      },
    },
  },
  hi: {
    nav: { home: 'होम', travel: 'यात्रा विवरण', wear: 'क्या पहनें' },
    heading: 'एक अकेली यात्रा से एक साझा भविष्य तक।',
    intro: 'बीर की पहाड़ियों की एक अकेली यात्रा से शुरू हुआ सफ़र, एक ऐसी यात्रा बन गया जो हम दोनों ने साथ तय की।',
    datesLine: '20 – 22 जनवरी 2027 · दिल्ली',
    checkoutNote: '22 जनवरी · चेक-आउट',
    closing: 'चार उत्सव। चार अध्याय। एक संपूर्ण यात्रा।',
    backHeading: 'हमारे साथ जश्न मनाने के लिए तैयार हैं?',
    backCta: 'यात्रा विवरण की पुष्टि करें',
    backDeadline: 'कृपया अपनी यात्रा जानकारी और पहचान पत्र की फोटो 31 अक्टूबर 2026 तक साझा करें।',
    wearHeading: 'क्या पहनें — एक नज़र में',
    wearIntro: 'सभी चार उत्सवों के लिए त्वरित संदर्भ। चित्र केवल प्रेरणा हैं, अनिवार्य खरीद नहीं।',
    men: 'पुरुष',
    women: 'महिलाएं',
    palette: 'रंग पट्टिका',
    dressCode: 'ड्रेस कोड',
    whatToWearEyebrow: 'क्या पहनें',
    chapterLabel: 'अध्याय',
    paletteDisclaimer: 'रंग पट्टिका चित्र की सजावटी रंग योजना है, यह पहनावे की शर्त नहीं है।',
    dow: { '2027-01-20': 'बुध 20 जनवरी', '2027-01-21': 'गुरु 21 जनवरी' } as Record<string, string>,
    dowShort: { '2027-01-20': 'बुध 20 जन', '2027-01-21': 'गुरु 21 जन' } as Record<string, string>,
    timeOfDay: { Morning: 'सुबह', Evening: 'शाम' } as Record<string, string>,
    chapters: {
      bloom: {
        event: 'मेहंदी', story: 'पहाड़ियों में दो अजनबी मिलते हैं।', shortLine: 'परंपराएं पूरे खिलाव में।',
        dressCode: 'हल्के हरे रंग की झलक के साथ फूलों और पेस्टल रंगों वाले परिधान',
        outfitExamples: ['फूलों वाले या पेस्टल कुर्ता सेट', 'फूलों वाली लहंगे, साड़ियां या सहज उत्सवी सेट'],
      },
      promise: {
        event: 'सगाई और कॉकटेल', story: 'दो जिंदगियां एक साझा भविष्य चुनती हैं।', shortLine: 'आने वाले कल के नाम एक जाम।',
        men: 'टक्सीडो और सूट',
        womenSourceVerbatim: 'नियॉन गाउन और इवनिंग इंडियन',
        paletteSourceVerbatim: 'कॉकटेल फॉर्मल · जूल टोन्स',
        note: 'नीचे दिखाई गई रंग पट्टिका (नेवी/एमराल्ड/प्लम/रूबी) एक अस्थायी जूल-टोन व्याख्या है, पुष्टि होना बाकी है — स्रोत में "नियॉन" भी लिखा है।',
      },
      romance: {
        event: 'हल्दी', story: 'हर कॉल, हर यात्रा और बीच का हर पल।', shortLine: 'प्रेम के रंग।',
        dressCode: 'हॉट पिंक', fabricNote: 'सहज, हल्दी के लिए उपयुक्त कपड़े',
        outfitExamples: ['हल्के हॉट-पिंक कुर्ता सेट', 'सहज हॉट-पिंक सलवार सूट या साड़ियां'],
      },
      legacy: {
        event: 'विवाह', story: 'यात्रा को उसका किनारा — उसका घर मिल जाता है।', shortLine: 'पीढ़ियों के लिए एक प्रेम।',
        dressCode: 'इंडियन फॉर्मल',
        outfitExamples: ['आइवरी या शैम्पेन शेरवानी और फॉर्मल इंडियन सेट', 'आइवरी, शैम्पेन या गोल्ड साड़ियां और लहंगे'],
      },
    },
  },
  gu: {
    nav: { home: 'હોમ', travel: 'મુસાફરીની વિગતો', wear: 'શું પહેરવું' },
    heading: 'એકલી મુસાફરીથી એક સહિયારા ભવિષ્ય સુધી.',
    intro: 'બીરની ટેકરીઓની એકલી સફરથી શરૂ થયેલી આ યાત્રા, એવી સફર બની ગઈ જે અમે બંનેએ સાથે મળીને કરી.',
    datesLine: '20 – 22 જાન્યુઆરી 2027 · દિલ્હી',
    checkoutNote: '22 જાન્યુઆરી · ચેક-આઉટ',
    closing: 'ચાર ઉત્સવો. ચાર પ્રકરણો. એક સંપૂર્ણ સફર.',
    backHeading: 'અમારી સાથે ઉજવણી કરવા તૈયાર છો?',
    backCta: 'મુસાફરીની વિગતોની પુષ્ટિ કરો',
    backDeadline: 'કૃપા કરી તમારી મુસાફરીની વિગતો અને ID ફોટો 31 ઓક્ટોબર 2026 સુધીમાં શેર કરો.',
    wearHeading: 'શું પહેરવું — એક નજરમાં',
    wearIntro: 'ચારેય ઉત્સવો માટે ઝડપી સંદર્ભ. ચિત્રો ફક્ત પ્રેરણા છે, ફરજિયાત ખરીદી નથી.',
    men: 'પુરુષો',
    women: 'મહિલાઓ',
    palette: 'રંગ પૅલેટ',
    dressCode: 'ડ્રેસ કોડ',
    whatToWearEyebrow: 'શું પહેરવું',
    chapterLabel: 'પ્રકરણ',
    paletteDisclaimer: 'રંગ પૅલેટ ચિત્રની સુશોભન રંગ યોજના છે, તે પોશાકની જરૂરિયાત નથી.',
    dow: { '2027-01-20': 'બુધ 20 જાન્યુઆરી', '2027-01-21': 'ગુરુ 21 જાન્યુઆરી' } as Record<string, string>,
    dowShort: { '2027-01-20': 'બુધ 20 જાન', '2027-01-21': 'ગુરુ 21 જાન' } as Record<string, string>,
    timeOfDay: { Morning: 'સવાર', Evening: 'સાંજ' } as Record<string, string>,
    chapters: {
      bloom: {
        event: 'મહેંદી', story: 'ટેકરીઓમાં બે અજાણ્યા લોકો મળે છે.', shortLine: 'પરંપરાઓ પૂર્ણ મોરમાં.',
        dressCode: 'આછા લીલા રંગની ઝલક સાથે ફૂલોવાળા અને પેસ્ટલ પોશાક',
        outfitExamples: ['ફૂલોવાળા અથવા પેસ્ટલ કુર્તા સેટ', 'ફૂલોવાળા લહેંગા, સાડીઓ અથવા સરળ ઉત્સવી સેટ'],
      },
      promise: {
        event: 'સગાઈ અને કોકટેલ', story: 'બે જિંદગીઓ એક સહિયારું ભવિષ્ય પસંદ કરે છે.', shortLine: 'આગળના રસ્તા માટે એક ટોસ્ટ.',
        men: 'ટક્સિડો અને સૂટ',
        womenSourceVerbatim: 'નિયોન ગાઉન અને ઇવનિંગ ઇન્ડિયન',
        paletteSourceVerbatim: 'કોકટેલ ફોર્મલ · જ્વેલ ટોન્સ',
        note: 'નીચે દર્શાવેલ રંગ પૅલેટ (નેવી/એમેરાલ્ડ/પ્લમ/રૂબી) એક કામચલાઉ જ્વેલ-ટોન અર્થઘટન છે, પુષ્ટિ બાકી છે — સ્રોતમાં "નિયોન" પણ લખેલું છે.',
      },
      romance: {
        event: 'હળદી', story: 'દરેક કૉલ, સફર અને વચ્ચેની દરેક ક્ષણ.', shortLine: 'પ્રેમના રંગો.',
        dressCode: 'હોટ પિંક', fabricNote: 'સરળ, હળદી માટે અનુકૂળ કાપડ',
        outfitExamples: ['હલકા હોટ-પિંક કુર્તા સેટ', 'સરળ હોટ-પિંક સલવાર સૂટ અથવા સાડીઓ'],
      },
      legacy: {
        event: 'લગ્ન', story: 'સફરને તેનો કિનારો — તેનું ઘર મળે છે.', shortLine: 'પેઢીઓ માટેનો પ્રેમ.',
        dressCode: 'ઇન્ડિયન ફોર્મલ',
        outfitExamples: ['આઇવરી અથવા શેમ્પેન શેરવાની અને ફોર્મલ ઇન્ડિયન સેટ', 'આઇવરી, શેમ્પેન અથવા ગોલ્ડ સાડીઓ અને લહેંગા'],
      },
    },
  },
}

type Strings = typeof strings.en
const LanguageContext = createContext<{
  lang: Lang
  setLang: (l: Lang) => void
  t: Strings
}>({ lang: 'en', setLang: () => {}, t: strings.en })

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>('en')
  return (
    <LanguageContext.Provider value={{ lang, setLang, t: strings[lang] }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLang() {
  return useContext(LanguageContext)
}
